apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-database-tier
  namespace: medai-prod
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: medai-backend
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-redis-tier
  namespace: medai-prod
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: medai-backend
      ports:
        - protocol: TCP
          port: 6379
