import skeletonModel from './bodyparts3dSkeletonModel.json';
import type { AnatomyViewerEntry } from './anatomyViewerTypes';

/**
 * The single source of truth mapping a backend `viewerKey` to asset mesh names.
 *
 * `viewerKey` is the backend's stable anatomy identity; mesh names belong to whichever skeleton
 * asset is bundled. They are deliberately not the same string, so swapping the asset means editing
 * this file only — no component performs its own mesh-name check.
 *
 * Mesh lookup is normalised (case, underscores, hyphens and spaces are ignored), so `Humerus_R`,
 * `humerus_r` and `HumerusR` all match the entry below. A materially different naming scheme
 * (for example `Right_Humerus`) should be added here as an extra mesh name rather than handled
 * inside a component.
 */
export const anatomyViewerManifest: Readonly<Record<string, AnatomyViewerEntry>> = {
  'skeleton.humerus.right': {
    meshNames: ['Humerus_R'],
    focusRegion: 'right_upper_arm',
    coveredStructures: ['Humerus'],
  },
  'skeleton.humerus.left': {
    meshNames: ['Humerus_L'],
    focusRegion: 'left_upper_arm',
    coveredStructures: ['Humerus'],
  },
  'skeleton.femur.right': {
    meshNames: ['Femur_R'],
    focusRegion: 'right_thigh',
    coveredStructures: ['Femur'],
  },
  'skeleton.femur.left': {
    meshNames: ['Femur_L'],
    focusRegion: 'left_thigh',
    coveredStructures: ['Femur'],
  },

  // The shoulder is a joint region, not a bone. It is rendered as the girdle that forms it and is
  // never collapsed to the humerus alone.
  'skeleton.shoulder.right': {
    meshNames: ['Scapula_R', 'Clavicle_R', 'Humerus_R'],
    focusRegion: 'right_shoulder_girdle',
    coveredStructures: ['Scapula', 'Clavicle', 'Humerus (head)'],
  },
  'skeleton.shoulder.left': {
    meshNames: ['Scapula_L', 'Clavicle_L', 'Humerus_L'],
    focusRegion: 'left_shoulder_girdle',
    coveredStructures: ['Scapula', 'Clavicle', 'Humerus (head)'],
  },

  // The knee joint is femur + tibia + patella. It is never collapsed to the femur alone.
  'skeleton.knee.right': {
    meshNames: ['Femur_R', 'Tibia_R', 'Patella_R'],
    focusRegion: 'right_knee',
    coveredStructures: ['Femur (distal)', 'Tibia (proximal)', 'Patella'],
  },
  'skeleton.knee.left': {
    meshNames: ['Femur_L', 'Tibia_L', 'Patella_L'],
    focusRegion: 'left_knee',
    coveredStructures: ['Femur (distal)', 'Tibia (proximal)', 'Patella'],
  },

  // The ankle joint is tibia + fibula + talus. It is never collapsed to the tibia alone.
  'skeleton.ankle.right': {
    meshNames: ['Tibia_R', 'Fibula_R', 'Talus_R'],
    focusRegion: 'right_ankle',
    coveredStructures: ['Tibia (distal)', 'Fibula (distal)', 'Talus'],
  },
  'skeleton.ankle.left': {
    meshNames: ['Tibia_L', 'Fibula_L', 'Talus_L'],
    focusRegion: 'left_ankle',
    coveredStructures: ['Tibia (distal)', 'Fibula (distal)', 'Talus'],
  },

  'nervous.brain': {
    meshNames: [
      'CerebralHemisphere_R',
      'CerebralHemisphere_L',
      'Midbrain',
      'Pons',
      'Cerebellum',
      'Medulla',
      'Hypothalamus',
      'Epithalamus',
      'ThirdVentricle',
      'FourthVentricle',
    ],
    focusRegion: 'head',
    coveredStructures: ['Brain', 'Brainstem', 'Cerebellum', 'Ventricles'],
  },

  'respiratory.lung.right': {
    meshNames: ['Lung_R'],
    focusRegion: 'right_chest',
    coveredStructures: ['Lung'],
  },
  'respiratory.lung.left': {
    meshNames: ['Lung_L'],
    focusRegion: 'left_chest',
    coveredStructures: ['Lung'],
  },

  'urinary.kidney.right': {
    meshNames: ['Kidney_R'],
    focusRegion: 'right_flank',
    coveredStructures: ['Kidney'],
  },
  'urinary.kidney.left': {
    meshNames: ['Kidney_L'],
    focusRegion: 'left_flank',
    coveredStructures: ['Kidney'],
  },
};

/**
 * Namespace prefixes this viewer renders. Everything else is honestly reported as unsupported —
 * this stays a small explicit allow-list (rather than "anything in the manifest") so a finding for
 * a genuinely unbuilt system (e.g. cardiac, hepatic) lands on the "not supported yet" message
 * instead of a confusing missing-mesh error.
 */
export const SUPPORTED_VIEWER_KEY_PREFIXES = ['skeleton.', 'nervous.brain', 'respiratory.lung.', 'urinary.kidney.'];

/**
 * Metadata for the bundled skeleton, generated by scripts/anatomy/build-bodyparts3d-skeleton.mjs
 * from the official BodyParts3D 4.0 archive. Single source of truth for the model path, its mesh
 * inventory, the verified license and the required attribution.
 */
export const skeletonModelMetadata = skeletonModel;

/** Mesh names actually present in the bundled model, straight from the build. */
export const bundledSkeletonMeshNames: string[] = skeletonModel.meshes.map((mesh) => mesh.mesh);

const modelUrlOverride = import.meta.env.VITE_ANATOMY_SKELETON_MODEL_URL?.trim();
/** Set the override to "none" to force the development placeholder. */
const placeholderForced = modelUrlOverride === 'none' || modelUrlOverride === 'off';

/**
 * URL of the licensed skeleton GLB.
 *
 * Defaults to the bundled BodyParts3D-derived model; an override exists so a deployment can serve
 * the asset from a CDN, or a developer can fall back to the schematic placeholder.
 */
export const skeletonModelUrl: string | null = placeholderForced
  ? null
  : modelUrlOverride || skeletonModel.modelPath;

/** True when the viewer is rendering the real licensed asset rather than the placeholder. */
export const usingBundledSkeletonModel: boolean = skeletonModelUrl === skeletonModel.modelPath;

/** Attribution required by the asset license. Verified against the official license page. */
export const skeletonModelAttribution: string | null = placeholderForced
  ? null
  : import.meta.env.VITE_ANATOMY_SKELETON_MODEL_ATTRIBUTION?.trim() || skeletonModel.attribution;

export const skeletonModelLicense: string | null = placeholderForced
  ? null
  : import.meta.env.VITE_ANATOMY_SKELETON_MODEL_LICENSE?.trim() || skeletonModel.license;

export const skeletonModelLicenseUrl: string = skeletonModel.licenseUrl;
