apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "med-ai-assistant.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "med-ai-assistant.name" . }}-backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "med-ai-assistant.name" . }}-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "med-ai-assistant.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backendPort }}
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
