apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "med-ai-assistant.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "med-ai-assistant.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "med-ai-assistant.name" . }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "med-ai-assistant.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontendPort }}
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
