package com.medai.chat.enums;

public enum SafetyFlag {
    RED_FLAG_EMERGENCY,
    ALLERGY_CONFLICT_DETECTED,
    POTENTIAL_INJECTION,
    OUT_OF_DOMAIN,
    OFF_LABEL_USE,
    UNCERTAINTY_DISCLAIMER
}
